[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  included_files = ["**"]
  external_node_modules = ["nodemailer", "busboy"]

[functions.send-ticket]
  raw_body = true